### ISSUE TITLE
Unexpected token error

### ISSUE THREAD

**Issue by methnen** [scottalguire/constomatic#1]
Was excited to try this out as it sounded perfect for my needs. However, when I try to use it I get the following error:

```
/node_modules/constomatic/index.js:16
    ...settings
    ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/jpoitra/mamp/go-v3/wp-content/themes/gigaom/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
```

I don't know a ton about node.js development but the `...settings` and later `...config` portions of the code do seem possibly problematic almost like you intended something to be there but then never got to it.

Totally possible that I'm just doing something stupid though too.

Any help would be greatly appreciated. :)

**Comment by scottalguire** [comment]
When I released this I didn't bother to transpile the modern Javascript features down to ES5 because my team is using modern Node. The JavaScript spread operator [didn't get full support](https://node.green/#ES2018-features-object-rest-spread-properties) until Node 8.6. If you were to update node I suspect that would solve the issue. I will release a more optimized build when I have time.

Thanks for checking it out, hope that solves your problem.

**Comment by methnen** [comment]
Ah, that makes sense. Sadly won't work for me then as the framework I'm currently stuck in breaks in newer versions of Node. 

Appreciate you responding in any case.
